### ISSUE TITLE
Page Total in case of Multipage print

### ISSUE THREAD

**Issue by KrishnaSoftwareSolution** [DavBfr/dart_pdf#1077]
How to print page total at page footer if we have contents in table (i.e. Amount total per page wise in case of multipage where table expanded to another page)   ??

**Comment by techttiru** [comment]
> 

@KrishnaSoftwareSolution , @DavBfr - Hi, I am also facing the problem of page total. is there a way to do this? is there a way we can find out the row number or before goes to next page?

**Comment by DavBfr** [comment]
I don't have a solution. This would require a new dedicated Table widget that does it.

**Comment by KrishnaSoftwareSolution** [comment]
Can you please explain how a dedicated table can keep track of the current
page running total ?

**Comment by KrishnaSoftwareSolution** [comment]
Can you please explain how a dedicated table can keep track of the current
page running total ?

**Comment by DavBfr** [comment]
A `SpanningWidget` has a state that gets saved/restored when needed by the layout engine to keep track of where it is at the rendering state: 
* First Layout with an infinite height that overflows the page.
* Second Layout with the page size to properly position the page content
* loop over for the next page.
The state is always reset to the content it was at the beginning of a page it renders so that you can keep track of the total in there.

**Comment by KrishnaSoftwareSolution** [comment]
Can you please write with example ?

**Comment by DavBfr** [comment]
You have access to the whole source code.

**Comment by KrishnaSoftwareSolution** [comment]
The facility that we found in for example FPDF in php, is somewhere missing in this library.
When you go depth there are many tools that should be there for developers.

**Comment by techttiru** [comment]
@DavBfr  - I see there is a object in footer callback under context called "context.page.content" but its not having the valid data at the time footer callback. but if we dig into the save method, during post processing i see this content object has been populated and seems to be having each page data. Is there a way to access this object in footer callback?

Also, i see a logic in multiple widget to identify whether new page needed or not based on the size of the rows. can we give a call back whenever new page is added? but i see you are taking all the children first and calculating the size of each children to see whether new page needed or not. Not sure whether you can give a call back to add additional children in it.

apart from this, i also tried to use Page widget instead of multipage widget to loop through the data and create new page every time. but the problem that i see in this approach is, for ex, if each page is taking 35 rows (according to our constant row size. if row size is dynamic then its problem), then we can achieve it.  even though if we take this approach and if we loop through until 40 rows per page then Page widget does not throw any erorr stating whether all the 40 rows are rendered in single page. if not, until what rows this has been rendered. because of this, we will not be able to know whether the row that we send is really rendered in the page. I understand that we need to measure this properly and send no.of rows to Page widget to render. but my case is, my row size will not be constant. for ex, if my text size in the row does not fit into single row then row will span into next line. so in this case, its really challenge to understand/measure how many lines each row is going to take.

is there a way to measure the each row height so that we can measure how many rows can be rendered? i saw your note in one of the post to use one of the method in Font object. can you please explain more to see how to measure.

as a work around, i am trying some unrealistic complex solution but its not consistent so far and still work in progress now.
I am trying to use the below code to measure the text width & height based on font size and then trying to measure whether how many lines this text will take. (in other words, for how many lines this text widget will auto span based on width that we provide to the container etc). 70 to 80 % it works and i am able to get the size of each row but its not a good solution and i dont know in what are the cases this will break. I want to follow some of the rule/logic that you have followed in the framework to measure the size. is there a way you can help to use any framework method to measure it or logic to measure it? I would really appreciate if any better solution or workaround to do it or any improvement that you could suggest for me.

```
  static SizeData calcTextSize(String text, pw.TextStyle pwTextStyle) {
    final style = TextStyle(fontSize: pwTextStyle.fontSize);
    final TextPainter textPainter = TextPainter(
      text: TextSpan(text: text, style: style),
      textDirection: TextDirection.ltr,
      textScaleFactor: WidgetsBinding.instance.window.textScaleFactor,
    );

    return SizeData(
        width: textPainter.size.width, height: textPainter.size.height);
  }
```

**Comment by DavBfr** [comment]
There is an easier way to calculate the size of any Widget: use `Widget.measure`

```dart
 pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.LayoutBuilder(
            builder: (context, constraints) {
              final ct = pw.Container(
                margin: pw.EdgeInsets.all(20),
                child: pw.Text('Hello World!'),
              );

              final size = pw.Widget.measure(ct,
                  context: context, constraints: constraints);

              print(size);

              return ct;
            },
          );
        },
      ),
    );
```

You can measure the size of the whole table to see if it fits. If not, remove some data and try again.

**Comment by techttiru** [comment]
> There is an easier way to calculate the size of any Widget: use `Widget.measure`
> 
> ```dart
>  pdf.addPage(
>       pw.Page(
>         pageFormat: format,
>         build: (context) {
>           return pw.LayoutBuilder(
>             builder: (context, constraints) {
>               final ct = pw.Container(
>                 margin: pw.EdgeInsets.all(20),
>                 child: pw.Text('Hello World!'),
>               );
> 
>               final size = pw.Widget.measure(ct,
>                   context: context, constraints: constraints);
> 
>               print(size);
> 
>               return ct;
>             },
>           );
>         },
>       ),
>     );
> ```
> 
> You can measure the size of the whole table to see if it fits. If not, remove some data and try again.

@DavBfr  - Thanks much for the response!.. This is exactly i was looking for and nice to see this feature already available. I am able to achieve what i wanted to do using this measure method.
actually this answers my other post as well that i had raised and you can close the same. 
[https://github.com/DavBfr/dart_pdf/issues/1112](https://github.com/DavBfr/dart_pdf/issues/1112)

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
