### ISSUE TITLE
Add number of copies

### ISSUE THREAD

**Issue by Shams-Mahmoud** [DavBfr/dart_pdf#1083]
how to add number of copies 
ex- i need to print one page 3 times how can i do this?

**Comment by DavBfr** [comment]
You have a pages parameter where you can set [1, 2, 2, 2, 3, 4]

**Comment by Shams-Mahmoud** [comment]
![label counter](https://user-images.githubusercontent.com/94101772/174990769-d7224a00-c8e7-4143-82c5-8287d95adc77.jpg)
the number of copies option not showing

**Comment by Shams-Mahmoud** [comment]
any solution

**Comment by Shams-Mahmoud** [comment]
![Capture](https://user-images.githubusercontent.com/94101772/175267635-37419925-ffb8-470c-a6f9-81959e68d054.PNG)
@DavBfr  the number of copies option not appear in printer settings

**Comment by DavBfr** [comment]
Yes, that's not implemented. If you need it, you can implement it, PR is welcome.

**Comment by DavBfr** [comment]
> @DavBfr pleas describe how to using on flutter windows desktop

There is nothing specific. It works out of the box.

**Comment by techttiru** [comment]
> You have a pages parameter where you can set [1, 2, 2, 2, 3, 4]

Hi @DavBfr , can you please explain this option? i want to print 80mm print receipt twice. every receipt, i need 2 copies. one for customer and another one for tracking. what is the page parameter option and where should i set this option?

i am creating my 80mm page using addPage function as below. where where should i set this page parameter? any example would be greatly appreciated!!!
```
 pdf.addPage(
    pw.Page(
      pageTheme: pw.PageTheme(
        theme: pw.ThemeData(
            defaultTextStyle: pw.TextStyle(
                font: tamilFont, fontBold: tamilFont, fontSize: 10.0)),
        orientation: pw.PageOrientation.portrait,
        pageFormat: const PdfPageFormat(
          80 * mm,
          double.infinity,
          marginTop: 5 * mm,
          marginBottom: 5 * mm,
          marginLeft: 2 * mm,
          marginRight: 15 * mm,
        ),
      ),
      build: (context) {
//* here all my code and logic
      }
)
)
```

**Comment by DavBfr** [comment]
It's when you run layoutPdf that you can specify the pages. For a 2 pages document, use [0,1,0,1] to print twice.

**Comment by techttiru** [comment]
@DavBfr - Hi thanks for responding. in the below code, where should i use this?

```
Future<bool> gereratePdf80MMSize(
  Event eventdata,
  EventAttendeeEntry eventAttendeeEntry,
  String typeOfReceipt,
) async {
  return await Printing.layoutPdf(
      onLayout: (format) =>
          _generatePdf(eventdata, eventAttendeeEntry, typeOfReceipt));
}
```

i see the below options in layoutPdf but not able to related which attribute accepts [0,1,0,1]. can you please explain in little detail?

```
  static Future<bool> layoutPdf({
    required LayoutCallback onLayout,
    String name = 'Document',
    PdfPageFormat format = PdfPageFormat.standard,
    bool dynamicLayout = true,
    bool usePrinterSettings = false,
  }) {
    return PrintingPlatform.instance.layoutPdf(
      null,
      onLayout,
      name,
      format,
      dynamicLayout,
      usePrinterSettings,
    );
  }
```

**Comment by techttiru** [comment]
@DavBfr - Hi, your response would be appreciated as its holding me to go to live? Quick response would be really appreciated!

**Comment by techttiru** [comment]
@DavBfr Thanks for responding. its basically duplicating the  `pdf.addPage()` ?. because this is where i am creating who logic. so i want the same copy once again, then create one more page with  same logic? is that not unnecessary of drawing the pdf twice?

I was trying to see, how to print one pdf but two copies. I tried changing the setting in printer setting. so when i try to print, its opening up the pdf with print layout where i make copies from 1 to 2. by this way, its printing twice. but the problem in this approach is, every print i need to make change the copy from 1 to 2.

is there a way we can preserve the user printer settings and make use for printing automatically ? i tried this `bool usePrinterSettings = true` option but it didn't help me.

**Comment by DavBfr** [comment]
What about that:

```dart
OutlinedButton(
  child: const Text('Print'),
  onPressed: () async {
    final pdf = await _generatePdf(PdfPageFormat.a4, title);
    final printer = await Printing.pickPrinter(context: context);
    if (printer == null) return;
    for (var page = 0; page < 2; page++) {
      await Printing.directPrintPdf(
        printer: printer,
        onLayout: (_) => pdf,
      );
    }
  },
)
```

**Comment by techttiru** [comment]
@DavBfr  Thank you!. Yes, this should work out. here we generate the pdf once but we send to printer twice. I will test this and post if any additional question.

Thanks much for responding!..

**Comment by techttiru** [comment]
But one think i would like to add here. i am actually printing this using flutter web application. I understand we can't access (or security problem) the local printer from web application. but i wanted do in my case, so i use the below code to allow web application to open up printer dialog.
```
  return await Printing.layoutPdf(
      onLayout: (format) =>
          _generatePdf(eventdata, eventAttendeeEntry, typeOfReceipt));
```

but since this is going to pop up everytime, i used chrome command to bypass/ignore this pop printer dialog. this way, i am managing this direct printing access. so here based on your comment, i am thinking to call the below function only once
`_generatePdf(eventdata, eventAttendeeEntry, typeOfReceipt);`

but call this below twice
`  return await Printing.layoutPdf()`

for ex: as you explained
```
final pdf = await _generatePdf(PdfPageFormat.a4, title);
for (var page = 0; page < 2; page++) {
      await Printing.layoutPdf(
        onLayout: (_) => pdf,
      );
    }
```
