### ISSUE TITLE
Split a Table in 2 pages

### ISSUE THREAD

**Issue by carpentierchloe** [DavBfr/dart_pdf#1140]
My table has dynamic rows. But if I have too much rows, I have got the error "This widget created more than 20 pages". What can I do ? If I limit the number of rows of my table, it does not fix the problem as they all do not have the same height.

**Comment by MichelMelhem** [comment]
Modidy the ```maxPages``` argument in Page

**Comment by function1983** [comment]
@MichelMelhem I think this is actually a bug and maxPages doesn't solve the problem.

For example, my Table has only 50 TableRow all with same height. One page can display 30 TableRow. Now I have 50 means which should fit nicely in 2 pages, but as soon as I have 31 TableRow, pdf will spit out the "max 20 pages" error. Increase maxPages to a high number (say 100) doesn't help.

If I manually split into two tables (30+20) then pdf doesn't have any problem display two tables into 2 pages.

I think that's why @carpentierchloe is asking how to split the table into 2 pages, **dynamically**.

**Comment by MichelMelhem** [comment]
> display

@function1983 I think you are right. I'm facing a similar issue in #1141.

**Comment by carpentierchloe** [comment]
@function1983 Yes you have understand my issue, is there a solution ? or an alternative one ?

**Comment by MichelMelhem** [comment]
any updates ?

**Comment by Psyphant** [comment]
This issue is a big blocker because the table row height is dynamic in my project, so I can't even split it manually into multiple pages. 
@DavBfr Can you please fix it in return for some coffee? :)
