### ISSUE TITLE
How to remove the default spacing of the layout and set margin 0 on all sides of all pages?

### ISSUE THREAD

**Issue by jazzbpn** [DavBfr/dart_pdf#116]
pdf.addPage(MultiPage(
      pageFormat: PdfPageFormat.a5,
      margin: EdgeInsets.only(left: 5, top: 5, right: 5, bottom: 5),

**_At the right side it shows more white spacing. How can we achieve all layout margin with 5.0?_**

**Comment by DavBfr** [comment]
You have to create a PdfPageFormat without any margin, as they are the minimal margin applied.
```dart
PdfPageFormat.a4.applyMargin(left:0, top:0, right:0, bottom:0)
```

**Comment by jazzbpn** [comment]
Already tried with this code. _It work for left, top and bottom_ and **Fails to work for RIGHT margin.**

**Comment by DavBfr** [comment]
It's not a margin, you're trying to fit an A5 document into a Letter paper. The aspect ratio is not the same, and the OS (Android) tries to fit but it induces some blank area.
When you use the layoutPdf function, you can't force a page format. The user decides, according to his printer. That's why the callback passes the current page format. It can be called many times when the user changes the orientation or paper size. If you want to see the real pdf file, choose A5 as paper format, or use a pdf viewer plugin, like flutter_full_pdf_viewer.
