### ISSUE TITLE
Printing PDF does not honour margins set

### ISSUE THREAD

**Issue by callumclift** [DavBfr/dart_pdf#124]
**Describe the bug**
When printing a PDF the print preview is cutting off the top of my PDF. I'm guessing this may be down to the printing package not honouring the margins of the PDF.

However when using the share function then selecting the print option the print preview is perfect and is correctly taking into account the margins.

**To Reproduce**

This is the code i'm using for printing the PDF:

`        await Printing.layoutPdf(
            onLayout: (PdfPageFormat format) async => pdf.save());
`

**Screenshots**

When using the print functionality the screenshot shows that it is cutting off the title of the PDF at the top of the page 'MAINTENANCE/SERVICE CHECKLIST'

<img width="508" alt="Screenshot 2019-08-02 at 05 13 03" src="https://user-images.githubusercontent.com/40245055/62344080-81848680-b4e4-11e9-9018-347e4a7f7e29.png">

Whereas when using the share option then selecting print the full original PDF is shown:

<img width="492" alt="Screenshot 2019-08-02 at 05 13 41" src="https://user-images.githubusercontent.com/40245055/62344107-97924700-b4e4-11e9-9a6b-3b9fc32b88a1.png">

Any ideas on how i can fix this? i've got both the latest versions of the pdf and printing package installed, thanks.

**Comment by DavBfr** [comment]
That's because you assume the paper dimensions are constant, but you don't decide the paper used, only the user does.
That's why await Printing.layoutPdf( ); passes the page format to the callback.
You have to repaint the full Pdf inside this function for the given dimensions. If you don't, iOS will try to fit your document inside the paper you have in your printer and create margins on sides or top/bottom.

**Comment by callumclift** [comment]
Ok thanks i'll give it a go and hopefully it will sort it out 🙏

**Comment by callumclift** [comment]
Awesome that's worked thanks a lot 🙏
