### ISSUE TITLE
unable to display the document

### ISSUE THREAD

**Issue by abdulashifaachu** [DavBfr/dart_pdf#1614]
![WhatsApp Image 2024-02-23 at 6 25 26 PM](https://github.com/DavBfr/dart_pdf/assets/117439908/430f4cd6-9788-4fae-a0a9-2f52c1ffcd0f)
here when i run locally its loading after deploying the website its showing like this ,here i only gave a text and a image that is network and its url is from an api so can anyone please suggest me the issue ,why its not loading after hosting

**Comment by abdulashifaachu** [comment]
anyone please help me with this

**Comment by bksbora** [comment]
What u want to show ? Be sure that u have used async func to fetch data before open pdf . if you summerize i would like to help :)

**Comment by irajeshh** [comment]
Not only for images, even Text widgets are also not showing in released web.
But works fine on running --release mode.
Also no error showing in console.

Also I tried to downgrade to old versions of pdf & print plugins. None of them worked, but the same plugins I used on flutter project SDK was `sdk: ">=3.0.2 <4.0.0"` now I'm using flutter version `3.19.1 stable` where it doesn't work.

```
// ignore_for_file: public_member_api_docs

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart' as printing;

class TempPrintPage extends StatelessWidget {
  const TempPrintPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return printing.PdfPreview(
      build: (format) => _generatePdf(format, 'title1'),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pw.Document document = pw.Document();

    document.addPage(
      pw.MultiPage(
        build: (pw.Context context) => [
          pw.Text('title'),
        ],
      ),
    );
    return document.save();
  }
}

```

**Comment by bksbora** [comment]
Brother where you came from ? ahahahah  :) You can use this empty pdf :D

```dart

import 'dart:typed_data';

import 'package:bkswebpanel/core/themes/app_theme.dart';
import 'package:flutter/material.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PackingListPdf extends StatefulWidget {
  const PackingListPdf({super.key});

  @override
  State<PackingListPdf> createState() => PackingListPdfState();
}

class PackingListPdfState extends State<PackingListPdf> {
  @override
  Widget build(BuildContext context) {
    const double inch = 72.0;
    const double cm = inch / 2.54;
    return Scaffold(
      appBar: AppBar(
        iconTheme: IconThemeData(
          size: 30,
          color: AppTheme().yesil, // Change the color here
        ),
        backgroundColor: AppTheme().kirlibeyaz,
      ),
      body: Container(
          height: Get.height,
          color: AppTheme().kirlibeyaz,
          child: PdfPreview(
            pdfFileName: 'Test',
            maxPageWidth: (Get.height) * 25 / 29.7,
            build: (format) => _generatePdf(
              // ? Veriyi Pdf'e Aktarma!
              // Margin
              const PdfPageFormat(21.0 * cm, 29.7 * cm, marginAll: 0.5 * cm),
            ),
          )),
    );
  }

  Future<Uint8List> _generatePdf(
// ? Aktarılan Veriyi Çekme!

    PdfPageFormat format,
  ) async {
    final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);

    // ignore: non_constant_identifier_names
    final FinalPDF = [pw.SizedBox(child: pw.Text("Deneme"))];
    pdf.addPage(
// Page Ayarları
      pw.MultiPage(
          maxPages: 100,
          theme: pw.ThemeData.withFont(
            base: await PdfGoogleFonts.openSansRegular(),
            bold: await PdfGoogleFonts.openSansBold(),
            icons: await PdfGoogleFonts.materialIcons(), // this line
          ),
          pageFormat: format,
          orientation: pw.PageOrientation.portrait,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          build: (context) {
            return FinalPDF;
          }),
    );

    return pdf.save();
  }
}```

**Comment by irajeshh** [comment]
I've checked both the old and new versions of the printing plugin, but none of them worked.
The error occurs only when after hosting the release build on a server. (I use firebase hosting).
Running in debugging mode & release mode it works well on localhost.
(Tested on All browsers).

I've found the location of the error message as here:
![image](https://github.com/DavBfr/dart_pdf/assets/85046336/e74e907c-cdc9-4914-8cfb-f3664b513812)


As I just want to print instead of previewing, I tried to use the onPressed function of the print button(Which will be shown on debugging mode) which is located here:
![image](https://github.com/DavBfr/dart_pdf/assets/85046336/c6794814-0370-4e04-a651-dcd3f575ae8a)
This one throwed error in web console released to Platform._unsuported operation


Then I try to download the file instead of showing preview or doing direct printing without preview, by using the code of Share button see below image for location:
![image](https://github.com/DavBfr/dart_pdf/assets/85046336/ae26c4b6-efb0-4967-8340-e05d000898cc)


This one also throwed error.


Final fix for my project:
My purpose is to generate PDF and download it. So I used pdf printing preview only on development and then when I release it to live, I simply download the file instead of printing it.
In case the user want to print it, they can open it at the same moment in chrome and print it.
The code I used to download the generated pdf is below:


  ```
Future<void> download() async {
    try {
      pdf.PdfPageFormat pageFormat = pdf.PdfPageFormat.a4;
      final Uint8List bytes = await _generatePdf(pageFormat);
      AnchorElement()
        ..href = Uri.dataFromBytes(bytes, mimeType: 'application/pdf').toString()
        ..download = 'document.pdf'
        ..style.display = 'none'
        ..click();
    } catch (e) {
      print('error while Downloading pdf: $e');
    }
  }
```

   ```
Future<Uint8List> _generatePdf(pdf.PdfPageFormat format) async {
    final pw.Document document = pw.Document();
    document.addPage(
      pw.MultiPage(
        build: (pw.Context context) => [
          pw.Text('title'),
          pw.Text('title2'),
        ],
      ),
    );
    return await document.save();
  }
```

**Comment by irajeshh** [comment]
@bksbora Ah you are right, it was my mistake as I put it inside a dialogue in this project, but on the previous one I pushed it to a separate page with size constraints to take full height and width of the device.

Now I set the height to the dialogue and the issue is resolved. In case there is w warning or error message in development that would save 2hrs. Any how thanks for the intimation, and I request you to change the way you are mentioning others in github. As a developer, try to keep git as gentle as possible instead of using words to degrade someone. By the way thanks.

**Comment by bksbora** [comment]
@irajeshh  neh i just wanted to say we were discussing this topic : unable to display the document  => then you ask something middle of it without giving any description info . Anyway , sorry if i offended you .

**Comment by irajeshh** [comment]
@bksbora I didn't ask anything off the topic. I also faced the problem so I commented my code snippet in which I faced the issue.
And I didn't offend Just the words you used **`(Brother where you came from ? ahahahah :) )`** that's what I tried to convey. By the way no problem, your solution was more valuable than the method of response.

**Comment by abdulashifaachu** [comment]
guyss i have solved the error by adding the code above the head inside index.html please go through the readme in the pub.dev

**Comment by rohintoncollins** [comment]
I got this working finally. Seems there was a bug which was fixed 
![image](https://github.com/DavBfr/dart_pdf/assets/54895992/1ee1c1d2-6c9d-4764-bca2-d1a2ada71fc4)

However, I was using the latest versions of pdf and printing
```
  pdf: ^3.10.8
  printing: ^5.12.0
```
I switched back to the latest common version:
```
  pdf: ^3.10.5
  printing: ^5.11.1
```
and it started working in release mode.
I then updated back to the latest versions and it continued to work. I did put in a few flutter clean's but previously this hadn't worked. So not really sure what the issue was. Perhaps something was cached incorrectly somewhere. But working now on latest versions.

**Comment by rohintoncollins** [comment]
This may help: https://github.com/DavBfr/dart_pdf/issues/1614#issuecomment-2093460760

**Comment by AtiaDjaberDev** [comment]
same problem when deploy not work 
i use latest release (printing: ^5.13.1) 
my flutter version(3.22.0)

**Comment by SilviaCebrian** [comment]
> same problem when deploy not work i use latest release (printing: ^5.13.1) my flutter version(3.22.0)

Try putting this in the index:

  <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.min.js" type="text/javascript"></script>

**Comment by AtiaDjaberDev** [comment]
same problem i add it like that:
<script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.min.js" type="text/javascript"></script>
</head>
 and try:
  <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.min.js" type="text/javascript">
  </script>
</body>
@SilviaCebrian

**Comment by SilviaCebrian** [comment]
try this:

 <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc =
      "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.worker.min.js";
    pdfRenderOptions = {
      // where cmaps are downloaded from
      cMapUrl: "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/cmaps/",
      // The cmaps are compressed in the case
      cMapPacked: true,
      // any other options for pdfjsLib.getDocument.
      // params: {}
    };
  </script>

I had the same problem and although I added the libraries it still didn't work, only in local. Try also with a clean just in case.

**Comment by AtiaDjaberDev** [comment]
Thank you very much,the clean command solved my issue
@SilviaCebrian
