### ISSUE TITLE
Unable to add SVG File

### ISSUE THREAD

**Issue by mainakshil** [DavBfr/dart_pdf#289]
I have tried using png file, it's working fine. But when I am trying to use svg file it's not working. Is this possible to add svg, or this will be a feature request?

const imageProvider = const AssetImage('assets/images/doc_chat.svg');
final PdfImage image = await pdfImageFromImageProvider(pdf: doc.document, image: imageProvider );

**Comment by DavBfr** [comment]
SVG is out of scope for this library. Still the Shape widget can draw a SVG path. Look at PdfLogo:
https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/widgets/placeholders.dart#L65

**Comment by cassioseffrin** [comment]
Hello @DavBfr ,

1st: pardon for ask in a closed issue. 
2nd: congrats for your amazing flutter library

3th: I have followed your link above and I have succeed, however this process of converting a svg path to Shape is not easy to automate. I know you don't have plans to support SVG in pdf lib, but may someone else can help to make it happen with this amazing lib:  https://pub.dev/packages/flutter_svg. If you know another way to automatize this conversion from svg to shape may you can give me an advice . Otherwise I will convert all my svg to png and then use ordinary images on pdf.

Thks in advance!

**Comment by DavBfr** [comment]
See https://github.com/DavBfr/dart_pdf/blob/master/test/golden/widgets-svg.pdf
