### ISSUE TITLE
Textpainter to calculate text dimensions?

### ISSUE THREAD

**Issue by bramvbilsen** [DavBfr/dart_pdf#378]
Is it currently possible to measure the width and height of a pdf `Text` widget? In Flutter, I can normally use a `TextPainter` to layout a piece of text and as a result get its dimensions. This'd be really convenient to have to manually split a big container across pages.

**Comment by DavBfr** [comment]
You can use the Text widget and call layout() on it. It will update its box attribute with the bounding box.

**Comment by jakobleck** [comment]
Sorry to reuse this old thread, but do you have a code example?

The thing is, I am currently doing some text size calculations for a pdf (and, if necessary, shortening of the text), and to test the layout TextPainter is not accurate since the sizing seems to be different from the pdf layout. But the solution proposed here requires creating a separate pw.Document for the test layout and calling save() on it. And once you do this multiple times, it is quite slow and not really comparable to the solution with TextPainter. Unless I am missing something...?
