### ISSUE TITLE
print downloaded pdf 

### ISSUE THREAD

**Issue by sidharathjain2** [DavBfr/dart_pdf#402]
This is an
 awesome package but my issue is that I have a downloaded pdf in download folder and I want to print it
like the same way

**Comment by DavBfr** [comment]
You can load the pdf using the regular `pdf = await File('my-file.pdf').readAsBytes();` and pass it to layoutPdf:
`Printing.layoutPdf(onLayout: (_) => pdf);`

**Comment by sidharathjain2** [comment]
Thanks Sir, but there is a problem when I preview with it then the page is shown at the left side  not in the center

**Comment by DavBfr** [comment]
I don't know what you're talking about. A screenshot would be useful.

**Comment by ydotmalik** [comment]
I'm not sure pdf_crypto will do what I want.

I created a password protected PDF file outside of dart_pdf and passed it to ```Printing.layoutPdf()```. I get the following exception:
```
E/AndroidRuntime(13348): java.lang.RuntimeException: Cannot print a password protected PDF file
E/AndroidRuntime(13348): 	at android.print.PrintManager$PrintDocumentAdapterDelegate$MyHandler.handleMessage(PrintManager.java:1101)
...
```

This is expected, but if I created a password protected PDF file using pdf_crypto and try to print it, won't I get the same behavior?

What I want to do:
- generate a PDF using dart_pdf
- pass it to ```Printing.layoutPdf()```
- since it isn't possible to prevent the user from saving the PDF from the print preview screen, I want to at least prevent the user from printing the saved PDF again. AFAIK, I have no control over the file once it is saved as PDF from the preview screen.
