### ISSUE TITLE
Implementation issue

### ISSUE THREAD

**Issue by primekhan555** [DavBfr/dart_pdf#598]
flutter printing package is not working in release APK it is logging this issue **Error getting printing info: MissingPluginException(No implementation found for method printingInfo on channel net.nfet.printing)**
and on screen it says unable to display document
my flutter version is 1.22
printing version is `printing: ^4.1.0`
pdf version is `pdf: ^2.1.0

**Comment by MostafaDadkhah** [comment]
me too

**Comment by DavBfr** [comment]
Upgrade to the last version: printing: 5.0.3

**Comment by MostafaDadkhah** [comment]
I have this issue in 5.0.3 ,,, printing in windows works but in android have this issuse

**Comment by DavBfr** [comment]
Missing listPrinters is totally normal: on Android, there is no API to list the printers. That's supported only on macOS, Windows, and Linux.

**Comment by MostafaDadkhah** [comment]
You mean, we can't print a document on Android?

**Comment by DavBfr** [comment]
You can print using Printing.layoutPdf()

**Comment by rommank** [comment]
> You can print using Printing.layoutPdf()

Could you please tell me how can I embed Printing.layoutPdf() as a Flutter screen to my Android Project. I would like to get the printing layout right after onClick of a button in Android. 
Thanks in advance!

**Comment by DavBfr** [comment]
It's all in the documentation: https://pub.dev/packages/printing#examples

**Comment by rommank** [comment]
> It's all in the documentation: https://pub.dev/packages/printing#examples

I could not find the case I am aiming for in the documentation(Click On button in Android native activity -> Invoke Printing.layoutPdf() in Flutter -> Open Printing Layout).
Maybe I not getting something right.

I've found a solution with PdfPreview I thought(Click On button in Android native activity -> show PdfPreview() in Flutter ->  Click on a print button -> Open Printing Layout).  
But I am getting the same issue as @primekhan555 pointed out.
Is there a way to return a proper Widget with Printing.layoutPdf()?
At the moment the only workaround I have is to call a blank Flutter screen from Android native and call a Printing.layoutPdf() at start.
This sends me to a printing layout.
But in this case, in order to go back to Android screen, I have to go back twice(to blank Flutter screen -> to Android Activity). 
I hope it does make sense.

**Comment by rommank** [comment]
> It's all in the documentation: https://pub.dev/packages/printing#examples

I was able to make PdfPreview() work. I just had to upgrade to package to the latest version.
Thanks for your effort.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
