### ISSUE TITLE
PdfPageFormat.roll57 and PdfPageFormat.roll80

### ISSUE THREAD

**Issue by BangPei** [DavBfr/dart_pdf#616]
i'm trying to print my receipt, but  when i set PdfPageFormat to PdfPageFormat.roll57 or PdfPageFormat.roll80 always throw error like this : PageFormat: "Page 161.5748031496063xInfinity margins:14.173228346456694, 14.173228346456694, 14.173228346456694, 14.173228346456694" pageFormat.height > 0 && pageFormat.height < double.infinity.
i change to PdfPageFormat.a4 , a3 ,a5 etc except roll57 and roll58 working well.

when i try to hard code PdfPageFormat(58 * (72 / 25.4), 200,marginAll: 2) i'm setting height from double.infinity to 200 working well.

is it some bugs or i'm wrong when use it?
can you help me please help??

**Comment by DavBfr** [comment]
roll57 and roll80 are infinite length papers, so you have to somehow limit the height.
You can't Center() a widget on an infinite or undefined dimension, right?

**Comment by BangPei** [comment]
now im using this code only.
Printing.layoutPdf(
    format: PdfPageFormat(55 * (72 / 25.4), 200,marginAll: 0),
    onLayout: (pageFormat) async =>buildPdf(pageFormat)
);

**Comment by usamaKabir07** [comment]
I'm having a same problem, can anyone help?

**Comment by SalemAlnakhbi** [comment]
> I'm having a same problem, can anyone help?

i just tried what he says but i am not sure if it is the right sol to do,

pageFormat: const PdfPageFormat(55 * (72 / 25.4), 200, marginAll: 0),

**Comment by xavierslee** [comment]
Tried out @SalemAlnakhbi attempt but still feel like this is a temporary solution

double.infinity executes a nan error so you have to set a max height limit.

I think its fine because most thermal printers will stop printing once all the visible text is printer,
it will not print the entire 297mm page.

 `final roll80format = PdfPageFormat(72 *(72/25.4) 297*(72/25.4), marginLeft:15,);
 `
roll80 format has a 72 by 297 dimensions, and you mulitply by (72/25.4) because you want to get the dimensions in mm

I think its usually in pixels? 

 i added margin left because epson printers tend to have larger space on the right
