### ISSUE TITLE
Pdf Landscape Orientation is not working as expected

### ISSUE THREAD

**Issue by VickyBOSS** [DavBfr/dart_pdf#756]
I created a pdf document with PageOrientation.landscape and the issues I'm facing are as follows -

1. It does not create pdf in landscape orientation, but it rotates the pdf page that makes pdf look ugly
2. Add a print option, why use save pdf or use a totally separate package just for printing

**Comment by DavBfr** [comment]
1. Yes, PageOrientation.landscape will rotate the content if needed. Because in the end, the end user's paper they have in their printer dictates the page format and orientation you'll have to use.
2. there are 2 packages because pdf does not rely on Flutter at all and can be used in a pure Dart command-line program or Angular Dart. the Printing package depends on Flutter to print any PDF on a real printer.
