### ISSUE TITLE
Preview my PDF document

### ISSUE THREAD

**Issue by carpentierchloe** [DavBfr/dart_pdf#893]
How to preview my PDF document without saving it ?

**Comment by DavBfr** [comment]
Like this: https://github.com/DavBfr/dart_pdf/blob/master/printing/example/lib/main.dart

**Comment by carpentierchloe** [comment]
Thank you. I already use it, but it shows the PDF with a very bad quality (wrong colors, borders who does not appear...). Is there another solution ?

**Comment by DavBfr** [comment]
What OS and Flutter flavor are you using? It shows correctly on all platforms.

**Comment by carpentierchloe** [comment]
Android and last Flutter version.

**Comment by DavBfr** [comment]
Using the emulator? If not which Android version and make/model?

**Comment by carpentierchloe** [comment]
I am not using the Emulator, I am compiling directly on my phone (Huawei P30).
The quality of the PDF is good once loaded, but not the Preview.

**Comment by DavBfr** [comment]
Can you send a screenshot?

**Comment by carpentierchloe** [comment]
Le ven. 31 déc. 2021 à 13:33, David PHAM-VAN ***@***.***> a
écrit :

**Comment by carpentierchloe** [comment]
![Screenshot_20211231_133552](https://user-images.githubusercontent.com/61030036/147823843-4a434cfa-0432-448a-afa6-3a0e42ae6cbc.jpg)
![Screenshot_20211231_133612](https://user-images.githubusercontent.com/61030036/147823850-f6050e94-04d1-4df0-80de-977feed22f72.jpg)

**Comment by DavBfr** [comment]
One thing you can try is to change the render mode.
Search the file `android/src/main/java/net/nfet/flutter/printing/PrintingJob.java` and change `RENDER_MODE_FOR_PRINT` to `RENDER_MODE_FOR_DISPLAY` line 475.

Let me know if it changes anything.

**Comment by carpentierchloe** [comment]
I only have android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
I cannot find PrintingJob.java

**Comment by DavBfr** [comment]
Depending on your OS it's not on your project folder.
On macOS  and Linux it's at `~/.pub-cache/hosted/pub.dartlang.org/printing-5.6.6/`

**Comment by carpentierchloe** [comment]
I made a research on all files of my macbook, cannot find  PrintingJob.java :(

**Comment by carpentierchloe** [comment]
Is there an alternative solution to the package printing ?

**Comment by DavBfr** [comment]
I don't know, I'm the author of this one. that's all I know.

**Comment by DavBfr** [comment]
You can try adding this to your `pubspec.yaml` to test the beta version:

```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: printing
```

**Comment by carpentierchloe** [comment]
I am getting this error :

_Because every version of printing from git depends on pdf from hosted and myApp depends on pdf from git, printing from git is forbidden.
So, because myApp depends on printing from git, version solving failed.
pub get failed (1; So, because myApp depends on printing from git, version solving failed.)_

**Comment by DavBfr** [comment]
Did you use `dependency_overrides` or `dependency`?

**Comment by carpentierchloe** [comment]
My mistake, all apologies. However, it does not resolve the issue with the preview color/border :'(

**Comment by carpentierchloe** [comment]
With the "preview" I just need the user to see the pdf without being able to save/download it on his phone. Is there an alternative way than this preview functionality ?

**Comment by DavBfr** [comment]
You can just run a Printing.layoutPdf() it will show the print screen with a preview on iOS and Android.

**Comment by carpentierchloe** [comment]
The user must not be able to print it either :'(

**Comment by deakjahn** [comment]
There are many PDF viewers out there, if you don't need printing, you should use one of those. This package uses the platform renderer on Android that converts the PDF pages into bitmap images. While this is fine for some applications (including this one), it's not the right solution for display if you want to allow the user to zoom in. You need a viewer that draws the vector PDF content as vector graphics, not bitmaps, to maintain quality at higher zoom levels. In an app of mine I happen to use https://pub.dev/packages/flutter_pdfview but there are several similar ones.

Color differences are probably due to your original PDF being made for print, possibly using CMYK colors instead of RGB. But even with RGB, an RGB color triplet is never a precise description of a color. All colors are described and rendered according to a specific color space and the same numeric RGB value will often display differently on different devices.

The file mentioned is at `.pub-cache\hosted\pub.dartlang.org\printing-5.6.6\android\src\main\java\net\nfet\flutter\printing\PrintingJob.java`. The beginning of the path will depend on the platform.
